sudo: false
services: mongodb

notifications:
  email: false

language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - Gemfile
  - gemfiles/carrierwave-0.10.gemfile
  - gemfiles/carrierwave-0.11.gemfile
  - gemfiles/carrierwave-1.1.gemfile
  - gemfiles/carrierwave-1.2.gemfile
  - gemfiles/carrierwave-1.3.gemfile
  - gemfiles/carrierwave-2.0.gemfile
  - gemfiles/mongoid-3.gemfile
  - gemfiles/mongoid-4.gemfile
  - gemfiles/mongoid-5.gemfile
  - gemfiles/mongoid-6.gemfile
  - gemfiles/mongoid-7.gemfile

matrix:
  fast_finish: true
