name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb: [4.4]
        ruby: [2.4, 2.5, 2.6, 2.7]
        gemfile:
          - carrierwave-1.1
          - carrierwave-1.2
          - carrierwave-1.3
          - carrierwave-2.0
          - carrierwave-2.1
          - mongoid-6
          - mongoid-7
        include:
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-0.10" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "carrierwave-0.11" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "mongoid-3" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "mongoid-4" }
          - { mongodb: "4.4", ruby: "2.6", gemfile: "mongoid-5" }
    name: Ruby ${{ matrix.ruby }} with ${{ matrix.gemfile }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Set up MongoDB ${{ matrix.mongodb }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
